# Generated by Django 3.1.7 on 2021-03-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=60)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=60)),
                ('inn', models.CharField(max_length=24)),
            ],
        ),
    ]
