# Generated by Django 3.1.7 on 2021-03-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_delete_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='inn',
            field=models.CharField(max_length=128),
        ),
    ]
